// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"UI_Tools","status":false,"description":"| UI_Tools : Version - 1.0.0 | A plugin that adds easy to use UI tools.","parameters":{"windowTitleBar":"UI/title_bar","closeDefault":"UI/close","closeHover":"UI/close_over","closePressed":"UI/close_down","windowBackground":"UI/subarea_over","windowPanel":"UI/subpanel"}},
{"name":"Rosedale_SkillTree","status":false,"description":"| Rosedale Skill Tree : Version - 1.1.0 | A simple skill tree.","parameters":{"menuName":"Skill Tree","inMenu":"true","enableSwitch":"0","treeBackground":"","pointsName":"SP","pointsPerLevel":"1","bonusPointLevels":"5","gridSize":"36","lockIcon":"0","learnedIcon":"0","learnSe":"{\"name\":\"\",\"volume\":\"90\",\"pitch\":\"100\",\"pan\":\"0\"}","learnAnime":"0","cursorSprite":"","cursorFlashSpeed":"0.10","arrowColors":"{\"colorEnabled\":\"#cfb634\",\"outlineEnabled\":\"#ff7700\",\"colorDisabled\":\"#666666\",\"outlineDisabled\":\"#444444\"}"}},
{"name":"Rosedale_SkillTreeBuilder","status":false,"description":"| Skill Tree Builder : Version - 1.0.1 | A GUI for building skill trees in Rosedale Skill Tree Plugin.","parameters":{}},
{"name":"Rosedale_ABSTool","status":true,"description":"| UI_Tools : Version - 1.0.0 | A plugin that adds easy to use UI tools.","parameters":{}},
{"name":"Rosedale_ProjectSelect","status":true,"description":"| Project Select Scene : Version - 1.0.0 | Create a project select scene.","parameters":{}},
{"name":"Rosedate_CharacterEditor","status":true,"description":"| Character Editor Scene : Version - 1.0.0 | Add the character editor scene.","parameters":{}},
{"name":"Rosedale_CharacterMotions","status":true,"description":"| Character Actions : Version - 1.2.1 | Add actin animaitions to your characters.","parameters":{"motionData":"[]"}}
];
